### PR TITLE
Install juju directly from 2.9 branch

### PR DESCRIPTION
**Pull request by gabrielcocenza**
Until fix of https://github.com/juju/python-libjuju/issues/955 is released we need to install from the branch.

### CODE REVIEW

**Review by agileshaw — APPROVED** [review]
LGTM

**Review by rgildein — APPROVED** [review]
LGTM

**Review by aieri — APPROVED** [review]
LGTM, but how are we tracking the need to switch back to stable libjuju releases?

**Comment by gabrielcocenza** [comment]
> LGTM, but how are we tracking the need to switch back to stable libjuju releases?

Created the #135 to not lose track

**Pull request merged**
