### PR TITLE
Properly wrapping help messages

### PR DESCRIPTION
**Pull request by agileshaw**
`hypervisor` subcommand and `--verbose` option didn't have their help message correctly wrapped, making them hard to read in terminal. This patch addresses these issues and also ensures a maximum line length of 100.

fixes: #303

### CODE REVIEW

**Comment by rgildein** [comment]
> message

The first line is strange, is that bug or some issue during copy and paste? There is
```bash
^(help-message+176) 10:47:56 
Usage: cou plan hypervisors [options]
```
Also can we make the help even shorter?  The longest line is 124 characters.

**Comment by agileshaw** [comment]
@rgildein `^(help-message+176) 10:47:56 ` came from my shell setting (FISH). Updated it. 

And sure, I can further tidy up the help messages

**Comment by agileshaw** [comment]
Output from the latest update of this patch ("before" output can be found in #303):
```
$ cou plan hypervisors -h
Usage: cou plan hypervisors [options]

Show the steps for upgrading nova-compute machines.
This is possible only if control-plane has been fully upgraded,
otherwise an error will be thrown.

Note that only principal applications colocated with nova-compute units
that support action-managed upgrades are within the scope of this command.
Other principal applications (e.g. ceph-osd) and subordinates
can be upgraded via the data-plane subcommand.

Options:
  -h, --help            Show this help message and exit.
  --model MODEL_NAME    Set the model to operate on.
                        If not set, the currently active Juju model will be used.
  --backup, --no-backup
                        Include database backup step before cloud upgrade.
                        Default to enabling database backup.
  --force               Force the plan/upgrade of non-empty hypervisors.
  --verbose, -v         Increase logging verbosity in STDOUT.
                        Multiple 'v's yield progressively more detail (up to 4).
                        Note that by default the logfile will include standard logs
                        from juju and websockets, as well as debug logs from all other
                        modules. To also include the debug level logs from juju and
                        websockets modules, use the maximum verbosity.
  --quiet, -q           Disable output in STDOUT.
  --machine MACHINES, -m MACHINES
                        Specify machine id(s) to upgrade.
                        This option accepts a single machine id as well as a stringified
                        comma-separated list of ids, and can be repeated multiple times.
  --availability-zone AVAILABILITY_ZONES, --az AVAILABILITY_ZONES
                        Specify availability zone(s) to upgrade.
                        This option accepts a single availability zone as well as a
                        stringified comma-separated list of AZs, and can be repeated
                        multiple times.
```

**Review by rgildein — APPROVED** [review]

**Review by gabrielcocenza — APPROVED** [review]
Thanks for the improvement. LGTM

**Pull request merged**
