### PR TITLE
drop parallel for `cou plan`

### PR DESCRIPTION
**Pull request by rgildein**
Dropping option `parallel` for `plan` command.

Fixes: #110

### CODE REVIEW

**Review by agileshaw — CHANGES_REQUESTED** [review]
As we discussed today, since we should consider unit level parallel execution a default (automatically for control-plane components and grouped by AZ for data-plane components), we can drop `--parallel` option all together.

**Comment by rgildein** [comment]
Right now we are not ready for this, since it will required actually changing how we run UpgradeSteps. I think that we can merge this first and open another issue to drop it also from `run`.

**Review by agileshaw — APPROVED** [review]
For the moment, I'm ok with removing parallel feature for plan only. Please open an issue to track dropping it everywhere.

**Review by gabrielcocenza — APPROVED** [review]
LGTM

**Pull request merged**
