### PR TITLE
Fix doc builds

### PR DESCRIPTION
**Pull request by chanchiwai-ray**
Fix the documentation build failures: https://readthedocs.com/projects/canonical-charmed-openstack-upgrader/builds/

### CODE REVIEW

**Comment by samuelallan72** [comment]
While we're looking at docs fixes, can we also merge https://github.com/canonical/charmed-openstack-upgrader/pull/515 that fixes this issue:

> (how-to/different-model: line   20) broken    https://juju.is/docs/juju/environment-variables#heading--jujudata - Anchor 'heading--jujudata' not found

**Review by samuelallan72 — COMMENTED** [review]
It sounds like this was broken for a while - what do we need to do to avoid this in future?  Can we improve the workflow to check that docs build successfully in CI?

**Review by jneo8 — APPROVED** [review]

**Comment by jneo8** [comment]
> It sounds like this was broken for a while - what do we need to do to avoid this in future? Can we improve the workflow to check that docs build successfully in CI?

Shouldn't check by https://github.com/canonical/documentation-workflows ?

**Comment by chanchiwai-ray** [comment]
> It sounds like this was broken for a while - what do we need to do to avoid this in future? Can we improve the workflow to check that docs build successfully in CI?

There is a new(?) integration that does exactly this `docs/readthedocs.com:canonical-charmed-openstack-upgrader — Read the Docs build succeeded!`

**Comment by samuelallan72** [comment]
Ah awesome, good to see :+1:

**Review by samuelallan72 — APPROVED** [review]

**Pull request merged**
